[workspace]
resolver = "2"
members = [
    "dat-parser",
    "function-calculator",
    "lca-calculator", "ncbi",
    "tables-generator",
    "taxdmp-parser",
    "uniprot-parser",
    "uniprot-parser-tryptic",
    "utils"
]
