name: Database

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 1 * *'

jobs:
  generate_tsv_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cd scripts/rust-utils && cargo fetch
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Install required utilities
        run: |
          sudo apt-get update
          sudo apt-get -y install git curl unzip gawk pv wget uuid-runtime pigz lz4 parallel libxml2-utils
      - name: Prepare temporary directories
        run: mkdir -p "output" "unipept-temp"
      - name: Generate tsv.gz files
        shell: bash
        run: ./scripts/generate_sa_tables.sh --database-sources "swissprot" --output-dir "output" --temp-dir "unipept-temp"
      - name: Zip all tsv.gz files
        shell: bash
        run: cd output && zip -r "../suffix_array.zip" * && zip -u "../suffix_array.zip" ".version"
      - name: Upload or Update Release
        id: upload_or_update_release
        uses: softprops/action-gh-release@v1
        with:
          files: suffix_array.zip
          tag_name: database-${{ env.date }}
          name: Database ${{ env.date }}
          commitish: ${{ github.sha }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
